---
- hosts: masters
  become: true
  roles:
    - setup-master
    - configure-kubeconfig
    - install-cni
    - install-runtimes
    - setup-worker
- hosts: workers
  become: true
  roles:
  - install-cni
  - install-runtimes
  - setup-worker