---
- hosts: masters
  vars:
    delete_previous_k8s_install: True
    drain_node_defore_update_k8s: True
  become: true
  roles:
    - setup-master
    - configure-kubeconfig
    - install-cni
    - install-runtimes
    - setup-worker
- hosts: workers
  vars:
    delete_previous_k8s_install: True
    drain_node_defore_update_k8s: True
  become: true
  roles:
  - install-cni
  - install-runtimes
  - setup-worker